<template>
  <v-card class="pa-2" elevation="2">
    <v-list dense>
      <v-list-item
        v-for="item in componentList"
        :key="item.type"
        @dragstart="
          (e: DragEvent) =>
            onDragStart(e, item.type, item.label, item.styles, item.cssClass, item.props)
        "
      >
        <div draggable="true" class="w-100">
          <v-list-item-title>{{ item.label }}</v-list-item-title>
        </div>
      </v-list-item>
    </v-list>
  </v-card>
</template>

<script setup lang="ts">
import { useBuilderStore } from '@/_builder/stores/useBuilderStore';
interface CompList {
  type: string;
  label: string;
  cssClass?: string;
  styles?: Record<string, any>;
  props?: Record<string, any>;
}
const builder = useBuilderStore();
const exportsd = () => {
  console.log('Exporting...', builder);
  builder.exportToJsonFile('my-template.json');
};
const componentList: CompList[] = [
  {
    type: 'group',
    label: '그룹',
    styles: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
  },
  {
    type: 'v-btn',
    label: 'button',
    props: {
      // color: undefined,
      density: 'default',
      disabled: false,
      // elevation: undefined,
      exact: false,
      flat: false,
      // height: undefined,
      // href: undefined,
      // 'max-height': undefined,
      // 'max-width': undefined,
      // 'min-height': undefined,
      // 'min-width': undefined,
      readonly: false,
      size: 'default',
      slim: false,
      text: '버튼1',
      tile: false,
      // to: undefined,
      variant: 'elevated',
      // width: undefined,
    },
  },
  // { type: 'v-btn', label: 'button' },
  {
    type: 'v-text-field',
    label: 'input',
    props: {
      autofocus: false,
      clearable: false,
      density: 'default',
      details: false,
      direction: 'horizontal',
      dirty: false,
      disabled: false,
      flat: false,
      focused: false,
      'hide-details': true,
      'hide-spin-buttons': true,
      // hint: undefined,
      // id: undefined,
      // label: undefined,
      // 'max-width': undefined,
      // 'min-width': undefined,
      // name: undefined,
      // placeholder: undefined,
      // prefix: undefined,
      readonly: false,
      // rounded: undefined,
      tile: false,
      variant: 'filled',
      // width: undefined,
    },
  },
  {
    type: 'v-textarea',
    label: 'textarea',
    props: {
      autofocus: false,
      'auto-grow': false,
      clearable: false,
      counter: false,
      density: 'default',
      details: false,
      direction: 'horizontal',
      dirty: false,
      disabled: false,
      flat: false,
      focused: false,
      'hide-details': true,
      'hide-spin-buttons': true,
      // hint: undefined,
      // id: undefined,
      // label: undefined,
      // 'max-rows': undefined,
      // 'max-width': undefined,
      // 'min-width': undefined,
      // name: undefined,
      'no-resize': false,
      // placeholder: undefined,
      // prefix: undefined,
      readonly: false,
      // rounded: undefined,
      rows: 5,
      tile: false,
      variant: 'filled',
      // width: undefined,
    },
  },
  {
    type: 'v-combobox',
    label: 'combobox',
    props: {
      autofocus: false,
      clearable: false,
      density: 'default',
      details: false,
      direction: 'horizontal',
      disabled: false,
      eager: false,
      flat: false,
      focused: false,
      'hide-details': true,
      'hide-no-data': false,
      'hide-selected': false,
      'hide-spin-buttons': true,
      // hint: undefined,
      // id: undefined,
      items: [],
      'item-title': 'title',
      'item-value': 'value',
      // label: undefined,
      // 'max-width': undefined,
      // 'min-width': undefined,
      multiple: false,
      // name: undefined,
      'no-auto-scroll': false,
      'no-filter': false,
      'open-on-clear': false,
      // placeholder: undefined,
      readonly: false,
      // rounded: undefined,
      tile: false,
      variant: 'filled',
      // width: undefined,
    },
  },
  {
    type: 'v-checkbox',
    label: 'checkbox',
    props: {
      density: 'default',
      direction: 'horizontal',
      disabled: false,
      // 'false-value': undefined,
      focused: false,
      'hide-details': true,
      'hide-spin-buttons': true,
      // hint: undefined,
      // id: undefined,
      // label: undefined,
      // 'max-width': undefined,
      // 'min-width': undefined,
      multiple: false,
      // name: undefined,
      readonly: false,
      // 'true-value': undefined,
      // width: undefined,
    },
  },
  {
    type: 'v-file-input',
    label: 'file-input',
    props: {
      clearable: false,
      density: 'default',
      details: false,
      direction: 'horizontal',
      dirty: false,
      disabled: false,
      flat: false,
      focused: false,
      'hide-details': true,
      'hide-input': false,
      'hide-spin-buttons': true,
      // hint: undefined,
      // id: undefined,
      // label: undefined,
      // 'max-width': undefined,
      // 'min-width': undefined,
      multiple: false,
      // name: undefined,
      readonly: false,
      'show-size': false,
      // rounded: undefined,
      tile: false,
      variant: 'filled',
      // width: undefined,
    },
  },
  {
    type: 'v-select',
    label: 'select',
    props: {
      autofocus: false,
      clearable: false,
      density: 'default',
      details: false,
      direction: 'horizontal',
      disabled: false,
      eager: false,
      flat: false,
      focused: false,
      'hide-details': true,
      'hide-no-data': false,
      'hide-selected': false,
      'hide-spin-buttons': true,
      // hint: undefined,
      // id: undefined,
      items: [],
      'item-title': 'title',
      'item-value': 'value',
      // label: undefined,
      // 'max-width': undefined,
      // 'min-width': undefined,
      multiple: false,
      // name: undefined,
      'no-auto-scroll': false,
      'open-on-clear': false,
      readonly: false,
      // rounded: undefined,
      tile: false,
      variant: 'filled',
      // width: undefined,
    },
  },
  {
    type: 'v-switch',
    label: 'switch',
    props: {
      density: 'default',
      direction: 'horizontal',
      disabled: false,
      // 'false-value': undefined,
      flat: false,
      focused: false,
      'hide-details': true,
      'hide-spin-buttons': true,
      // hint: undefined,
      // id: undefined,
      // label: undefined,
      // 'max-width': undefined,
      // 'min-width': undefined,
      multiple: false,
      // name: undefined,
      readonly: false,
      // 'true-value': undefined,
      // width: undefined,
    },
  },
  {
    type: 'v-date-input',
    label: 'date-input',
    props: {
      'allowed-dates': [],
      'allowed-months': [],
      'allowed-years': [],
      autofocus: false,
      border: false,
      'cancel-text': '취소',
      clearable: false,
      density: 'default',
      details: false,
      direction: 'horizontal',
      dirty: false,
      disabled: false,
      divided: false,
      // elevation: undefined,
      flat: false,
      focused: false,
      height: false,
      'hide-actions': false,
      'hide-details': true,
      'hide-header': false,
      'hide-spin-buttons': true,
      'hide-weekdays': false,
      // hint: undefined,
      // id: undefined,
      // 'input-format': undefined,
      // label: undefined,
      // 'max-height': undefined,
      // 'max-width': undefined,
      // 'min-height': undefined,
      // 'min-width': undefined,
      // month: undefined,
      multiple: false,
      // name: undefined,
      'ok-text': '확인',
      // placeholder: undefined,
      // position: undefined,
      readonly: false,
      // rounded: undefined,
      'show-week': false,
      tile: false,
      variant: 'filled',
      'view-mode': 'month',
      // 'weekday-format': undefined,
      'weeks-in-month': 'static',
      // width: undefined,
      // year: undefined,
    },
  },
  {
    type: 'v-alert',
    label: 'alert',
    props: {
      border: false,
      // 'border-color': undefined,
      closable: false,
      // color: undefined,
      density: 'default',
      // elevation: undefined,
      // height: undefined,
      // 'max-height': undefined,
      // 'max-width': undefined,
      // 'min-height': undefined,
      // 'min-width': undefined,
      // position: undefined,
      prominent: false,
      rounded: false,
      // text: undefined,
      tile: false,
      // title: undefined,
      variant: 'flat',
      // width: undefined,
    },
  },
  {
    type: 'my-data-table',
    label: 'data table',
    props: {
      density: 'compact',
      'fixed-footer': false,
      'fixed-header': false,
      headers: [
        { title: 'ID', align: 'center', sortable: false, key: 'id' },
        { title: 'Plant', align: 'start', sortable: false, key: 'name' },
        { title: 'Light', align: 'end', key: 'light' },
        { title: 'Height', align: 'end', key: 'height' },
        { title: 'Pet Friendly', align: 'end', key: 'petFriendly' },
        { title: 'Price ($)', align: 'end', key: 'price' },
      ],
      items: [
        {
          id: '1',
          name: 'Fern',
          light: 'Low',
          height: '20cm',
          petFriendly: 'Yes',
          price: 20,
        },
      ],
      'hide-default-body': false,
      'hide-default-footer': false,
      'hide-default-header': false,
      'hide-no-data': false,
      'items-per-page': '10',
      loading: false,
      sticky: false,
    },
  },
  // {
  //   type: 'my-tabs',
  //   label: 'tabs',
  //   props: {
  //     'align-tabs': 'start',
  //     'center-active': false,
  //     density: 'default',
  //     disabled: false,
  //     'hide-slider': false,
  //     'selected-class': 'v-tab-item--selected',
  //     'show-arrows': false,
  //   },
  // },
  // { type: 'v-dialog', label: 'dialog' },
  // { type: 'v-tooltip', label: 'tooltip' },
  // { type: 'v-snackbar', label: 'snackbar' },
  // { type: 'v-card', label: 'card' },
  // { type: 'v-expansion-panels', label: 'expansion panels' },
  // { type: 'v-list', label: 'list' },
  // { type: 'v-treeview', label: 'treeview' },
  // { type: 'v-stepper', label: 'stepper' },
  // { type: 'v-pagination', label: 'pagination' },
  // { type: 'v-progress-circular', label: 'progress circular' },
  // { type: 'v-sheet', label: 'sheet' },
  {
    type: 'my-note-box',
    label: 'Note box',
    cssClass: '',
    styles: { border: '1px dashed #ccc', padding: '5px' },
  }, // 사용자 정의 컴포넌트
  {
    type: 'my-subject-text',
    label: 'Subject Text',
    cssClass: '',
    styles: { border: '1px dashed #ccc', padding: '5px' },
  }, // 사용자 정의 컴포넌트
  {
    type: 'my-page-title',
    label: 'Page Ttile',
    cssClass: '',
    styles: { border: '1px dashed #ccc', padding: '5px' },
  }, // 사용자 정의 컴포넌트
  {
    type: 'my-ck-editor',
    label: 'CKEditor',
    cssClass: '',
    styles: { border: '1px dashed #ccc', padding: '5px' },
  }, // CKEditor 컴포넌트
  {
    type: 'my-ag-grid',
    label: 'AG Grid',
    cssClass: '',
    styles: { border: '1px dashed #ccc', padding: '5px' },
  }, // AG Grid 컴포넌트
];

const onDragStart = (
  e: DragEvent,
  type: string,
  label: string,
  styles: any,
  cssClass: any,
  props: any
) => {
  e.dataTransfer?.setData('component-type', type);
  e.dataTransfer?.setData('component-label', label);
  e.dataTransfer?.setData('component-styles', JSON.stringify(styles || {}));
  e.dataTransfer?.setData('component-class', cssClass);
  e.dataTransfer?.setData('component-props', JSON.stringify(props || {}));
};
</script>
