// componentMap.ts
import MyDataTable from '@/_builder/components/custom/CustomDataTable.vue';
import MyAgGrid from '@/_builder/components/custom/CustomAgGrid.vue';
import MyCkEditor from '@/_builder/components/custom/CustomCkEditor.vue';
import MyPageTitle from '@/_builder/components/custom/CustomPageTitle.vue';
import MySubjectText from '@/_builder/components/custom/CustomSubjectText.vue';
import MyNoteBox from '@/_builder/components/custom/CustomNoteBox.vue';
import MyCarousel from '@/_builder/components/custom/CustomCarousel.vue';
import MyCard from '@/_builder/components/custom/CustomCard.vue';
import MyFooter from '@/_builder/components/custom/CustomFooter.vue';

// custom form
import MyInput from '@/_builder/components/custom/form/CustomInput.vue';
import MyAutocomplate from '@/_builder/components/custom/form/CustomAutocomplate.vue';
import MyTextarea from '@/_builder/components/custom/form/CustomTextarea.vue';
import MySelect from '@/_builder/components/custom/form/CustomSelect.vue';
import MyCheckboxGroup from '@/_builder/components/custom/form/CustomCheckboxGroup.vue';
import MyRadioGroup from '@/_builder/components/custom/form/CustomRadioGroup.vue';
import MyCombobox from '@/_builder/components/custom/form/CustomCombobox.vue';
import MyFileInput from '@/_builder/components/custom/form/CustomFileInput.vue';
import MySwitch from '@/_builder/components/custom/form/CustomSwitch.vue';
import MyDateInput from '@/_builder/components/custom/form/CustomDateInput.vue';
import MyFileUploader from '@/_builder/components/custom/form/CustomFileUploader.vue';

export const ComponentRegistry: any = {
  group: {
    label: '그룹',
    component: 'group',
    propsMeta: [
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'border', label: 'border', type: 'text' },
      { key: 'padding', label: '패딩 (padding)', type: 'text' },
      { key: 'display', label: 'Display', type: 'select', options: ['flex', 'grid', 'block'] },
      {
        key: 'flexDirection',
        label: 'Flex 방향',
        type: 'select',
        options: ['row', 'column', 'row-reverse', 'column-reverse'],
      },
      {
        key: 'justifyContent',
        label: '가로 정렬 (justify)',
        type: 'select',
        options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around'],
      },
      {
        key: 'alignItems',
        label: '세로 정렬 (align)',
        type: 'select',
        options: ['flex-start', 'center', 'flex-end', 'stretch'],
      },
      { key: 'gap', label: '갭 (gap)', type: 'text' },
      { key: 'backgroundColor', label: '배경색 (background color)', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'v-btn': {
    label: 'button',
    component: 'v-btn',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'text', label: 'text', type: 'text' },
      {
        key: 'color',
        label: 'color',
        type: 'select',
        options: ['primary', 'secondary', 'success'],
      },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'elevation', label: 'elevation', type: 'text' },
      { key: 'exact', label: 'exact', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'href', label: 'href', type: 'text' },
      { key: 'max-height', label: 'max-height', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-height', label: 'min-height', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      {
        key: 'size',
        label: 'size',
        type: 'select',
        options: ['x-small', 'small', 'default', 'large', 'x-large'],
      },
      { key: 'slim', label: 'slim', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      { key: 'to', label: 'to', type: 'text' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: ['flat', 'text', 'elevated', 'tonal', 'outlined', 'plain'],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'height', label: '높이', type: 'text' }
      //   ],
      // },
    ],
  },
  'my-text-field': {
    label: 'text-field',
    component: MyInput,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'dirty', label: 'dirty', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      // { key: 'value', label: 'value', type: 'text' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      { key: 'dataMapSchema', label: 'dataMapSchema', type: 'select', options: [] },
      { key: 'dataMapKey', label: 'dataMapKey', type: 'select', options: [] },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'min-height', label: '높이', type: 'text' },
      //   ],
      // },
    ],
  },
  'my-autocomplete': {
    label: 'autocomplete',
    component: MyAutocomplate,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      { key: 'chips', label: 'chips', type: 'boolean' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },

      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-no-data', label: 'hide-no-data', type: 'boolean' },
      { key: 'hide-selected', label: 'hide-selected', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },

      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      {
        key: 'items',
        label: '옵션 목록',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'title', label: 'Key', type: 'text' },
          { key: 'value', label: 'Value', type: 'text' },
        ],
      },
      { key: 'item-title', label: 'label', type: 'text' },
      { key: 'item-value', label: 'value', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'no-auto-scroll', label: 'no-auto-scroll', type: 'boolean' },
      { key: 'no-filter', label: 'no-filter', type: 'boolean' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },

      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      // { key: 'value', label: 'value', type: 'text' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-textarea': {
    label: 'textarea',
    component: MyTextarea,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      { key: 'auto-grow', label: 'auto-grow', type: 'boolean' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      { key: 'counter', label: 'counter', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'dirty', label: 'dirty', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-rows', label: 'max-rows', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'no-resize', label: 'no-resize', type: 'boolean' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'rows', label: 'rows', type: 'text' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'min-height', label: '높이', type: 'text' },
      //   ],
      // },
    ],
  },
  'v-checkbox': {
    label: 'checkbox',
    component: 'v-checkbox',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'hide-detail', label: 'hide-detail', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-checkbox-group': {
    label: 'checkbox-group',
    component: MyCheckboxGroup,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'hide-detail', label: 'hide-detail', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      {
        key: 'items',
        label: '옵션 목록',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'label', label: 'Label', type: 'text' },
          { key: 'value', label: 'Value', type: 'text' },
        ],
      },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-radio-group': {
    label: 'radio-group',
    component: MyRadioGroup,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'hide-detail', label: 'hide-detail', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'inline', label: 'inline', type: 'text' },
      {
        key: 'items',
        label: '옵션 목록',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'label', label: 'Label', type: 'text' },
          { key: 'value', label: 'Value', type: 'text' },
        ],
      },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-combobox': {
    label: 'combobox',
    component: MyCombobox,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'autofocus', label: 'disabled', type: 'boolean' },
      { key: 'placeholder', label: 'placeholder', type: 'text' },
      { key: 'clearable', label: 'clearable', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'eager', label: 'eager', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-no-data', label: 'hide-no-data', type: 'boolean' },
      { key: 'hide-selected', label: 'hide-selected', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      {
        key: 'items',
        label: '옵션 목록',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'title', label: 'Label', type: 'text' },
          { key: 'value', label: 'Value', type: 'text' },
        ],
      },
      { key: 'item-title', label: 'label', type: 'text' },
      { key: 'item-value', label: 'value', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'no-auto-scroll', label: 'no-auto-scroll', type: 'boolean' },
      { key: 'no-data-text', label: 'no-data-text', type: 'text' },
      { key: 'no-filter', label: 'no-filter', type: 'boolean' },
      { key: 'open-on-clear', label: 'open-on-clear', type: 'boolean' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-file-input': {
    label: 'file-input',
    component: MyFileInput,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'dirty', label: 'dirty', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-input', label: 'hide-input', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-select': {
    label: 'select',
    component: MySelect,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      { key: 'clearable', label: 'clearable', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'eager', label: 'eager', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-no-data', label: 'hide-no-data', type: 'boolean' },
      { key: 'hide-selected', label: 'hide-selected', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      {
        key: 'items',
        label: '옵션 목록',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'title', label: 'Key', type: 'text' },
          { key: 'value', label: 'Value', type: 'text' },
        ],
      },
      { key: 'item-title', label: 'label', type: 'text' },
      { key: 'item-value', label: 'value', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'no-auto-scroll', label: 'no-auto-scroll', type: 'boolean' },
      { key: 'no-data-text', label: 'no-data-text', type: 'text' },
      { key: 'open-on-clear', label: 'open-on-clear', type: 'boolean' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-switch': {
    label: 'switch',
    component: MySwitch,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'true-value', label: 'true-value', type: 'text' },
      { key: 'false-value', label: 'false-value', type: 'text' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'min-height', label: '높이', type: 'text' },
      //   ],
      // },
    ],
  },
  'v-chip': {
    label: 'chip',
    component: 'v-chip',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'color', label: 'color', type: 'text' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'href', label: 'href', type: 'text' },
      { key: 'pill', label: 'pill', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },

      {
        key: 'size',
        label: 'size',
        type: 'select',
        options: ['x-small', 'small', 'default', 'large', 'x-large'],
      },
      { key: 'text', label: 'text', type: 'text' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      { key: 'to', label: 'to', type: 'text' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: ['flat', 'text', 'elevated', 'tonal', 'outlined', 'plain'],
      },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'v-img': {
    label: 'img',
    component: 'v-img',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'alt', label: 'alt', type: 'text' },
      { key: 'cover', label: 'cover', type: 'boolean' },
      { key: 'color', label: 'color', type: 'text' },
      { key: 'gradient', label: 'gradient', type: 'text' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'inline', label: 'inline', type: 'boolean' },
      { key: 'lazy-src', label: 'lazy-src', type: 'text' },
      { key: 'max-height', label: 'max-height', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-height', label: 'min-height', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'src', label: 'src', type: 'text' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      { key: 'transition', label: 'transition', type: 'text' },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-date-input': {
    label: 'date-input',
    component: MyDateInput,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'allowed-dates', label: 'allowed-dates', type: 'text' },
      { key: 'allowed-months', label: 'allowed-months', type: 'text' },
      { key: 'allowed-years', label: 'allowed-years', type: 'text' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      { key: 'border', label: 'border', type: 'boolean' },
      { key: 'cancel-text', label: 'cancel-text', type: 'text' },
      // { key: 'control-height', label: 'control-height', type: 'text' },
      // { key: 'counter', label: 'counter', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'dirty', label: 'dirty', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'divided', label: 'divided', type: 'boolean' },
      { key: 'elevation', label: 'elevation', type: 'text' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'hide-actions', label: 'hide-actions', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-header', label: 'hide-header', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hide-weekdays', label: 'hide-weekdays', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'input-format', label: 'input-format', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'max-height', label: 'max-height', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'min-height', label: 'min-height', type: 'text' },
      { key: 'month', label: 'month', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'ok-text', label: 'ok-text', type: 'text' },
      {
        key: 'position',
        label: 'position',
        type: 'select',
        options: ['fixed', 'static', 'relative', 'absolute', 'sticky'],
      },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'show-week', label: 'show-week', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      {
        key: 'view-mode',
        label: 'view-mode',
        type: 'select',
        options: ['month', 'months', 'year'],
      },
      {
        key: 'weekday-format',
        label: 'weekday-format',
        type: 'select',
        options: ['long', 'short', 'narrow'],
      },
      {
        key: 'weeks-in-month',
        label: 'weeks-in-month',
        type: 'select',
        options: ['static', 'dynamic'],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'year', label: 'year', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-file-uploader': {
    label: 'file-upload',
    component: MyFileUploader,
    propsMeta: [
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'divider-text', label: 'divider-text', type: 'text' },
      { key: 'elevation', label: 'elevation', type: 'text' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'hide-browse', label: 'hide-browse', type: 'boolean' },
      { key: 'length', label: 'length', type: 'text' },
      { key: 'max-height', label: 'max-height', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-height', label: 'min-height', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      {
        key: 'position',
        label: 'position',
        type: 'select',
        options: ['fixed', 'static', 'relative', 'absolute', 'sticky'],
      },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'scrim', label: 'scrim', type: 'boolean' },
      { key: 'show-size', label: 'show-size', type: 'boolean' },
      { key: 'subtitle', label: 'subtitle', type: 'text' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      { key: 'title', label: 'title', type: 'text' },
      { key: 'width', label: 'width', type: 'text' },
    ],
  },
  'my-data-table': {
    label: 'data-table',
    component: MyDataTable,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'fixed-footer', label: 'fixed-footer', type: 'boolean' },
      { key: 'fixed-header', label: 'fixed-header', type: 'boolean' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'hide-default-body', label: 'hide-default-body', type: 'boolean' },
      { key: 'hide-default-footer', label: 'hide-default-footer', type: 'boolean' },
      { key: 'hide-default-header', label: 'hide-default-header', type: 'boolean' },
      { key: 'hide-no-data', label: 'hide-no-data', type: 'boolean' },
      {
        key: 'headers',
        label: 'Header',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'align', label: 'Align', type: 'text' },
          { key: 'key', label: 'Key', type: 'text' },
        ],
      },
      { key: 'items-per-page', label: 'items-per-page', type: 'text' },
      { key: 'loading', label: 'loading', type: 'boolean' },
      { key: 'sticky', label: 'sticky', type: 'boolean' },
      {
        key: 'striped',
        label: 'striped',
        type: 'select',
        options: ['odd', 'even'],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'height', label: '높이', type: 'text' }
      //   ],
      // },
    ],
  },
  // 'my-tabs': {
  //   label: 'tabs',
  //   component: MyTabs,
  //   propsMeta: [
  //     { key: 'wrapClass', label: 'wrapClass', type: 'text' },
  //     { key: 'class', label: 'css class', type: 'text' },
  //     { key: 'align-tabs', label: 'align-tabs', type: 'text' },
  //     { key: 'bg-color', label: 'bg-color', type: 'text' },
  //     { key: 'center-active', label: 'center-active', type: 'boolean' },
  //     { key: 'color', label: 'color', type: 'text' },
  //     {
  //       key: 'density',
  //       label: 'density',
  //       type: 'select',
  //       options: ['default', 'comfortable', 'compact'],
  //     },
  //     { key: 'disabled', label: 'disabled', type: 'boolean' },
  //     { key: 'height', label: 'height', type: 'text' },
  //     { key: 'hide-slider', label: 'hide-slider', type: 'boolean' },
  //     {
  //       key: 'items',
  //       label: 'items',
  //       type: 'array',
  //       itemType: 'object',
  //       itemFields: [
  //         { key: 'text', label: 'Title', type: 'text' },
  //         { key: 'to', label: 'To', type: 'text' },
  //         { key: 'color', label: 'Color', type: 'text' },
  //       ],
  //     },
  //     { key: 'selected-class', label: 'selected-class', type: 'text' },
  //     { key: 'show-arrows', label: 'show-arrows', type: 'boolean' },
  //     { key: 'slider-color', label: 'slider-color', type: 'text' },
  //   ],
  // },
  'my-note-box': {
    label: '노트박스',
    component: MyNoteBox,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'title', label: 'title', type: 'text' },
      { key: 'messageBefore', label: 'messageBefore', type: 'text' },
      { key: 'linkText', label: 'linkText', type: 'text' },
      { key: 'linkHref', label: 'linkHref', type: 'text' },
      { key: 'messageAfter', label: 'messageAfter', type: 'text' },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-subject-text': {
    label: 'subject text',
    component: MySubjectText,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'title', label: '타이틀제목', type: 'text' },
      {
        key: 'icon',
        label: '아이콘',
        type: 'text',
      },
      {
        key: 'iconSize',
        label: '아이콘 크기',
        type: 'select',
        options: ['1', '2', '3', '4', '5'],
      },
      {
        key: 'size',
        label: '폰트 사이즈',
        type: 'select',
        options: ['sm', 'md', 'lg', 'xl'],
      },
      {
        key: 'weight',
        label: '폰트 두께',
        type: 'select',
        options: ['normal', 'medium', 'bold'],
      },
      {
        key: 'divider',
        label: '구분선',
        type: 'select',
        options: [true, false],
      },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-page-title': {
    label: 'Page Title',
    component: MyPageTitle,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'title', label: '페이지타이틀', type: 'text' },
      {
        key: 'breadcrumbs',
        label: 'Breadcrumb',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'title', label: 'title', type: 'text' },
          { key: 'href', label: 'href', type: 'text' },
          { key: 'disabled', label: 'disabled', type: 'boolean' },
        ],
      },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-ag-grid': {
    label: 'AG GRid',
    component: MyAgGrid,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      {
        key: 'columnDefs',
        label: 'columnDefs',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'headerName', label: 'headerName', type: 'text' },
          { key: 'field', label: 'field', type: 'text' },
          { key: 'type', label: 'type', type: 'text' },
          { key: 'width', label: 'width', type: 'text' },
          { key: 'maxWidth', label: 'maxWidth', type: 'text' },
          { key: 'pinned', label: 'pinned', type: 'text' },
          { key: 'initialWidth', label: 'initialWidth', type: 'text' },
          { key: 'initialPinned', label: 'initialPinned', type: 'text' },
          { key: 'hide', label: 'hide', type: 'boolean' },
          { key: 'sort', label: 'sort', type: 'select', options: ['asc', 'desc'] },
          {
            key: 'filter',
            label: 'filter',
            type: 'select',
            options: [
              'agSetColumnFilter',
              'agMultiColumnFilter',
              'agNumberColumnFilter',
              'agDateColumnFilter',
            ],
          },
          { key: 'sortIndex', label: 'sortIndex', type: 'text' },
        ],
      },
      {
        key: 'defaultColDef',
        label: 'defaultColDef',
        type: 'object',
        itemFields: [
          { key: 'flex', label: 'flex', type: 'text' },
          { key: 'sortable', label: 'sortable', type: 'boolean' },
          { key: 'filter', label: 'filter', type: 'boolean' },
          { key: 'editable', label: 'editable', type: 'boolean' },
          // { key: 'width', label: 'width', type: 'text' },
        ],
      },
      { key: 'apiUrl', label: 'API URL', type: 'text' },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-ck-editor': {
    label: 'CKEditor',
    component: MyCkEditor,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-carousel': {
    label: 'Carousel',
    component: MyCarousel,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-card': {
    label: '카드',
    component: MyCard,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-footer': {
    label: 'Footer',
    component: MyFooter,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
};
