// componentMap.ts
import MyCard from '@/_builder/components/custom/MyCard.vue';
import MyAgGrid from '@/_builder/components/custom/CustomAgGrid.vue';
import MyCkEditor from '@/_builder/components/custom/CustomCkEditor.vue';
import MyPageTitle from '@/_builder/components/custom/CustomPageTitle.vue';
import MySubjectText from '@/_builder/components/custom/CustomSubjectText.vue';
import MyNoteBox from '@/_builder/components/custom/CustomNoteBox.vue';
export const ComponentRegistry: any = {
  group: {
    label: '그룹',
    component: 'group',
    propsMeta: [
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'border', label: 'border', type: 'text' },
      { key: 'padding', label: '패딩 (padding)', type: 'text' },
      { key: 'display', label: 'Display', type: 'select', options: ['flex', 'grid', 'block'] },
      {
        key: 'flexDirection',
        label: 'Flex 방향',
        type: 'select',
        options: ['row', 'column', 'row-reverse', 'column-reverse'],
      },
      {
        key: 'justifyContent',
        label: '가로 정렬 (justify)',
        type: 'select',
        options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around'],
      },
      {
        key: 'alignItems',
        label: '세로 정렬 (align)',
        type: 'select',
        options: ['flex-start', 'center', 'flex-end', 'stretch'],
      },
      { key: 'gap', label: '갭 (gap)', type: 'text' },
      { key: 'backgroundColor', label: '배경색 (background color)', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'v-btn': {
    label: 'btn',
    component: 'v-btn',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'ref', label: 'ref', type: 'text' },
      { key: 'text', label: 'text', type: 'text' },
      {
        key: 'color',
        label: 'color',
        type: 'select',
        options: ['primary', 'secondary', 'success'],
      },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'elevation', label: 'elevation', type: 'text' },
      { key: 'exact', label: 'exact', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'href', label: 'href', type: 'text' },
      { key: 'max-height', label: 'max-height', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-height', label: 'min-height', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      {
        key: 'size',
        label: 'size',
        type: 'select',
        options: ['x-small', 'small', 'default', 'large', 'x-large'],
      },
      { key: 'slim', label: 'slim', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      { key: 'to', label: 'to', type: 'text' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: ['flat', 'text', 'elevated', 'tonal', 'outlined', 'plain'],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'height', label: '높이', type: 'text' }
      //   ],
      // },
    ],
  },
  'v-text-field': {
    label: 'text-field',
    component: 'v-text-field',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'dirty', label: 'dirty', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      { key: 'value', label: 'value', type: 'text' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'min-height', label: '높이', type: 'text' },
      //   ],
      // },
    ],
  },
  'v-checkbox': {
    label: 'checkbox',
    component: 'v-checkbox',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'hide-detail', label: 'hide-detail', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  // 'v-radio': {
  //   label: 'radio',
  //   component: 'v-radio',
  //   propsMeta: [
  //     { key: 'class', label: 'css class', type: 'text' },
  //     { key: 'disabled', label: 'disabled', type: 'boolean' },
  //     {
  //       key: 'density',
  //       label: 'density',
  //       type: 'select',
  //       options: ['default', 'comfortable', 'compact'],
  //     },
  //     { key: 'false-value', label: 'false-value', type: 'text' },
  //     { key: 'inline', label: 'inline', type: 'boolean' },
  //     { key: 'id', label: 'id', type: 'text' },
  //     { key: 'label', label: 'label', type: 'text' },
  //     { key: 'name', label: 'name', type: 'text' },
  //     { key: 'readonly', label: 'readonly', type: 'boolean' },
  //     { key: 'true-value', label: 'true-value', type: 'text' },
  //   ],
  // },
  'v-combobox': {
    label: 'combobox',
    component: 'v-combobox',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'autofocus', label: 'disabled', type: 'boolean' },
      { key: 'placeholder', label: 'placeholder', type: 'text' },
      { key: 'clearable', label: 'clearable', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'eager', label: 'eager', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-no-data', label: 'hide-no-data', type: 'boolean' },
      { key: 'hide-selected', label: 'hide-selected', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      {
        key: 'items',
        label: '옵션 목록',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'title', label: 'Key', type: 'text' },
          { key: 'value', label: 'Value', type: 'text' },
        ],
      },
      { key: 'item-title', label: 'label', type: 'text' },
      { key: 'item-value', label: 'value', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'no-auto-scroll', label: 'no-auto-scroll', type: 'boolean' },
      { key: 'no-data-text', label: 'no-data-text', type: 'text' },
      { key: 'no-filter', label: 'no-filter', type: 'boolean' },
      { key: 'open-on-clear', label: 'open-on-clear', type: 'boolean' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'v-file-input': {
    label: 'file-input',
    component: 'v-file-input',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'dirty', label: 'dirty', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-input', label: 'hide-input', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'min-height', label: '높이', type: 'text' },
      //   ],
      // },
    ],
  },
  'v-select': {
    label: 'select',
    component: 'v-select',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      { key: 'clearable', label: 'clearable', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'eager', label: 'eager', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-no-data', label: 'hide-no-data', type: 'boolean' },
      { key: 'hide-selected', label: 'hide-selected', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      {
        key: 'items',
        label: '옵션 목록',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'title', label: 'Key', type: 'text' },
          { key: 'value', label: 'Value', type: 'text' },
        ],
      },
      { key: 'item-title', label: 'label', type: 'text' },
      { key: 'item-value', label: 'value', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'no-auto-scroll', label: 'no-auto-scroll', type: 'boolean' },
      { key: 'no-data-text', label: 'no-data-text', type: 'text' },
      { key: 'open-on-clear', label: 'open-on-clear', type: 'boolean' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'v-switch': {
    label: 'switch',
    component: 'v-switch',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'true-value', label: 'true-value', type: 'text' },
      { key: 'false-value', label: 'false-value', type: 'text' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'min-height', label: '높이', type: 'text' },
      //   ],
      // },
    ],
  },
  'v-textarea': {
    label: 'textarea',
    component: 'v-textarea',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      { key: 'auto-grow', label: 'auto-grow', type: 'boolean' },
      { key: 'counter', label: 'counter', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'dirty', label: 'dirty', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-rows', label: 'max-rows', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'no-resize', label: 'no-resize', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'rows', label: 'rows', type: 'text' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'min-height', label: '높이', type: 'text' },
      //   ],
      // },
    ],
  },
  'v-date-input': {
    label: 'date-input',
    component: 'v-date-input',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'allowed-dates', label: 'allowed-dates', type: 'text' },
      { key: 'allowed-months', label: 'allowed-months', type: 'text' },
      { key: 'allowed-years', label: 'allowed-years', type: 'text' },
      { key: 'clearable', label: 'Clearable', type: 'boolean' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      { key: 'border', label: 'border', type: 'boolean' },
      { key: 'cancel-text', label: 'cancel-text', type: 'text' },
      // { key: 'control-height', label: 'control-height', type: 'text' },
      // { key: 'counter', label: 'counter', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'dirty', label: 'dirty', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'divided', label: 'divided', type: 'boolean' },
      { key: 'elevation', label: 'elevation', type: 'text' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'hide-actions', label: 'hide-actions', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-header', label: 'hide-header', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hide-weekdays', label: 'hide-weekdays', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'input-format', label: 'input-format', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'max-height', label: 'max-height', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'min-height', label: 'min-height', type: 'text' },
      { key: 'month', label: 'month', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'ok-text', label: 'ok-text', type: 'text' },
      {
        key: 'position',
        label: 'position',
        type: 'select',
        options: ['fixed', 'static', 'relative', 'absolute', 'sticky'],
      },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'show-week', label: 'show-week', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      {
        key: 'view-mode',
        label: 'view-mode',
        type: 'select',
        options: ['month', 'months', 'year'],
      },
      {
        key: 'weekday-format',
        label: 'weekday-format',
        type: 'select',
        options: ['long', 'short', 'narrow'],
      },
      {
        key: 'weeks-in-month',
        label: 'weeks-in-month',
        type: 'select',
        options: ['static', 'dynamic'],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'year', label: 'year', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'min-height', label: '높이', type: 'text' },
      //   ],
      // },
    ],
  },
  // 'v-file-upload': {
  //   label: 'file-upload',
  //   component: 'v-file-upload',
  //   propsMeta: [
  //     { key: 'class', label: 'css class', type: 'text' },
  //     { key: 'clearable', label: 'Clearable', type: 'boolean' },
  //     {
  //       key: 'density',
  //       label: 'density',
  //       type: 'select',
  //       options: ['default', 'comfortable', 'compact'],
  //     },
  //     { key: 'disabled', label: 'disabled', type: 'boolean' },
  //     { key: 'divider-text', label: 'divider-text', type: 'text' },
  //     { key: 'elevation', label: 'elevation', type: 'text' },
  //     { key: 'height', label: 'height', type: 'text' },
  //     { key: 'hide-browse', label: 'hide-browse', type: 'boolean' },
  //     { key: 'length', label: 'length', type: 'text' },
  //     { key: 'max-height', label: 'max-height', type: 'text' },
  //     { key: 'max-width', label: 'max-width', type: 'text' },
  //     { key: 'min-height', label: 'min-height', type: 'text' },
  //     { key: 'min-width', label: 'min-width', type: 'text' },
  //     { key: 'multiple', label: 'multiple', type: 'boolean' },
  //     { key: 'name', label: 'name', type: 'text' },
  //     {
  //       key: 'position',
  //       label: 'position',
  //       type: 'select',
  //       options: ['fixed', 'static', 'relative', 'absolute', 'sticky'],
  //     },
  //     { key: 'rounded', label: 'rounded', type: 'boolean' },
  //     { key: 'scrim', label: 'scrim', type: 'boolean' },
  //     { key: 'show-size', label: 'show-size', type: 'boolean' },
  //     { key: 'subtitle', label: 'subtitle', type: 'text' },
  //     { key: 'tile', label: 'tile', type: 'boolean' },
  //     { key: 'title', label: 'title', type: 'text' },
  //     { key: 'width', label: 'width', type: 'text' },
  //     // {
  //     //   key: 'style',
  //     //   label: '스타일',
  //     //   type: 'object',
  //     //   fields: [
  //     //     { key: 'width', label: '너비', type: 'text' },
  //     //     { key: 'min-height', label: '높이', type: 'text' },
  //     //   ],
  //     // },
  //   ],
  // },
  'v-alert': {
    label: 'alert',
    component: 'v-alert',
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'text', label: 'text', type: 'text' },
      {
        key: 'border',
        label: 'border',
        type: 'select',
        options: ['top', 'end', 'bottom', 'start'],
      },
      { key: 'border-color', label: 'border-color', type: 'text' },
      { key: 'closable', label: 'closable', type: 'boolean' },
      { key: 'color', label: 'color', type: 'text' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'elevation', label: 'elevation', type: 'text' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'max-height', label: 'max-height', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-height', label: 'min-height', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      {
        key: 'position',
        label: 'position',
        type: 'select',
        options: ['fixed', 'static', 'relative', 'absolute', 'sticky'],
      },
      { key: 'prominent', label: 'prominent', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      { key: 'title', label: 'title', type: 'text' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: ['flat', 'text', 'elevated', 'tonal', 'outlined', 'plain'],
      },
      { key: 'width', label: 'width', type: 'text' },
      { key: 'exposeId', label: 'exposeId', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'height', label: '높이', type: 'text' }
      //   ],
      // },
    ],
  },
  'my-note-box': {
    label: '노트박스',
    component: MyNoteBox,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'title', label: 'title', type: 'text' },
      { key: 'messageBefore', label: 'messageBefore', type: 'text' },
      { key: 'linkText', label: 'linkText', type: 'text' },
      { key: 'linkHref', label: 'linkHref', type: 'text' },
      { key: 'messageAfter', label: 'messageAfter', type: 'text' },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  // 'my-card': {
  //   label: '카드',
  //   component: MyCard,
  //   propsMeta: [
  //     { key: 'title', label: '제목', type: 'text' },
  //     { key: 'content', label: '내용', type: 'textarea' },
  //     { key: 'color', label: '배경색', type: 'select', options: ['primary', 'info', 'warning'] },
  //   ],
  // },
  'my-subject-text': {
    label: 'subject text',
    component: MySubjectText,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'title', label: '타이틀제목', type: 'text' },
      {
        key: 'icon',
        label: '아이콘',
        type: 'text',
      },
      {
        key: 'iconSize',
        label: '아이콘 크기',
        type: 'select',
        options: ['1', '2', '3', '4', '5'],
      },
      {
        key: 'size',
        label: '폰트 사이즈',
        type: 'select',
        options: ['sm', 'md', 'lg', 'xl'],
      },
      {
        key: 'weight',
        label: '폰트 두께',
        type: 'select',
        options: ['normal', 'medium', 'bold'],
      },
      {
        key: 'divider',
        label: '구분선',
        type: 'select',
        options: [true, false],
      },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-page-title': {
    label: 'Page Title',
    component: MyPageTitle,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'title', label: '페이지타이틀', type: 'text' },
      {
        key: 'breadcrumb',
        label: 'breadcrumb',
        type: 'text',
      },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-ag-grid': {
    label: 'AG GRid',
    component: MyAgGrid,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
  'my-ck-editor': {
    label: 'CKEditor',
    component: MyCkEditor,
    propsMeta: [
      { key: 'wrapClass', label: 'wrapClass', type: 'text' },
      { key: 'class', label: 'css class', type: 'text' },

      { key: 'exposeId', label: 'exposeId', type: 'text' },
    ],
  },
};
