// componentMap.ts
import MyCard from '@/_builder/components/custom/MyCard.vue';
import MyAgGrid from '@/_builder/components/custom/CustomAgGrid.vue';
import MyCkEditor from '@/_builder/components/custom/CustomCkEditor.vue';
import MyPageTitle from '@/_builder/components/custom/CustomPageTitle.vue';
import MySubjectText from '@/_builder/components/custom/CustomSubjectText.vue';
import MyNoteBox from '@/_builder/components/custom/CustomNoteBox.vue';
export const ComponentRegistry: any = {
  'v-btn': {
    label: 'btn',
    component: 'v-btn',
    propsMeta: [
      { key: 'class', label: 'css class', type: 'text' },
      { key: 'text', label: 'text', type: 'text' },
      {
        key: 'color',
        label: 'color',
        type: 'select',
        options: ['primary', 'secondary', 'success'],
      },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'elevation', label: 'elevation', type: 'text' },
      { key: 'exact', label: 'exact', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'href', label: 'href', type: 'text' },
      { key: 'max-height', label: 'max-height', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-height', label: 'min-height', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      {
        key: 'size',
        label: 'size',
        type: 'select',
        options: ['x-small', 'small', 'default', 'large', 'x-large'],
      },
      { key: 'slim', label: 'slim', type: 'boolean' },
      { key: 'text', label: 'text', type: 'text' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      { key: 'to', label: 'to', type: 'text' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: ['flat', 'text', 'elevated', 'tonal', 'outlined', 'plain'],
      },
      { key: 'width', label: 'width', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'height', label: '높이', type: 'text' }
      //   ],
      // },
    ],
  },
  'v-text-field': {
    label: 'text-field',
    component: 'v-text-field',
    propsMeta: [
      { key: 'clearable', label: 'Clearable', type: 'radio' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'autofocus', label: 'autofocus', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'dirty', label: 'dirty', type: 'boolean' },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focus', label: 'focus', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'boolean' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'placeholder', label: 'placeholder', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
      // {
      //   key: 'style',
      //   label: '스타일',
      //   type: 'object',
      //   fields: [
      //     { key: 'width', label: '너비', type: 'text' },
      //     { key: 'min-height', label: '높이', type: 'text' },
      //   ],
      // },
    ],
  },
  'v-checkbox': {
    label: 'checkbox',
    component: 'v-checkbox',
    propsMeta: [
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'glow', label: 'glow', type: 'boolean' },
      { key: 'hide-detail', label: 'hide-detail', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'width', label: 'width', type: 'text' },
    ],
  },
  'v-combobox': {
    label: 'combobox',
    component: 'v-combobox',
    propsMeta: [
      { key: 'autofocus', label: 'disabled', type: 'boolean' },
      { key: 'clearable', label: 'clearable', type: 'boolean' },
      {
        key: 'density',
        label: 'density',
        type: 'select',
        options: ['default', 'comfortable', 'compact'],
      },
      { key: 'details', label: 'details', type: 'boolean' },
      { key: 'direction', label: 'direction', type: 'select', options: ['horizontal', 'vertical'] },
      { key: 'disabled', label: 'disabled', type: 'boolean' },
      { key: 'eager', label: 'eager', type: 'boolean' },
      { key: 'flat', label: 'flat', type: 'boolean' },
      { key: 'focused', label: 'focused', type: 'boolean' },
      { key: 'grow', label: 'grow', type: 'boolean' },
      { key: 'hide-details', label: 'hide-details', type: 'boolean' },
      { key: 'hide-no-data', label: 'hide-no-data', type: 'boolean' },
      { key: 'hide-selected', label: 'hide-selected', type: 'boolean' },
      { key: 'hide-spin-buttons', label: 'hide-spin-buttons', type: 'boolean' },
      { key: 'hint', label: 'hint', type: 'text' },
      { key: 'id', label: 'id', type: 'text' },
      {
        key: 'items',
        label: '옵션 목록',
        type: 'array',
        itemType: 'object',
        itemFields: [
          { key: 'title', label: 'Key', type: 'text' },
          { key: 'value', label: 'Value', type: 'text' },
        ],
      },
      { key: 'item-title', label: 'label', type: 'text' },
      { key: 'item-value', label: 'value', type: 'text' },
      { key: 'label', label: 'label', type: 'text' },
      { key: 'max-width', label: 'max-width', type: 'text' },
      { key: 'min-width', label: 'min-width', type: 'text' },
      { key: 'multiple', label: 'multiple', type: 'boolean' },
      { key: 'name', label: 'name', type: 'text' },
      { key: 'no-auto-scroll', label: 'no-auto-scroll', type: 'boolean' },
      { key: 'no-data-text', label: 'no-data-text', type: 'text' },
      { key: 'no-auto-scroll', label: 'no-auto-scroll', type: 'boolean' },
      { key: 'no-filter', label: 'no-filter', type: 'boolean' },
      { key: 'open-on-clear', label: 'open-on-clear', type: 'boolean' },
      { key: 'placeholder', label: 'placeholder', type: 'text' },
      { key: 'readonly', label: 'readonly', type: 'boolean' },
      { key: 'rounded', label: 'rounded', type: 'boolean' },
      { key: 'tile', label: 'tile', type: 'boolean' },
      {
        key: 'variant',
        label: 'variant',
        type: 'select',
        options: [
          'outlined',
          'plain',
          'underlined',
          'filled',
          'solo',
          'solo-inverted',
          'solo-filled',
        ],
      },
      { key: 'width', label: 'width', type: 'text' },
    ],
  },
  'v-textarea': {
    label: 'textarea',
    component: 'v-textarea',
    propsMeta: [
      { key: 'clearable', label: 'Clearable', type: 'radio' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
    ],
  },
  // { type: 'v-combobox', label: 'combobox' },
  // { type: 'v-checkbox', label: 'checkbox' },
  // { type: 'v-radio-group', label: 'radio' },
  // { type: 'v-switch', label: 'switch' },
  // { type: 'v-dialog', label: 'dialog' },
  // { type: 'v-tooltip', label: 'tooltip' },
  // { type: 'v-snackbar', label: 'snackbar' },
  // { type: 'v-alert', label: 'alert' },
  // { type: 'v-card', label: 'card' },
  // { type: 'v-tabs', label: 'tabs' },
  // { type: 'v-expansion-panels', label: 'expansion panels' },
  // { type: 'v-data-table', label: 'data table' },
  // { type: 'v-list', label: 'list' },
  // { type: 'v-treeview', label: 'treeview' },
  // { type: 'v-stepper', label: 'stepper' },
  // { type: 'v-pagination', label: 'pagination' },
  group: {
    label: '그룹',
    component: 'group',
    propsMeta: [
      { key: 'width', label: 'width', type: 'text' },
      { key: 'height', label: 'height', type: 'text' },
      { key: 'display', label: 'Display', type: 'select', options: ['flex', 'grid', 'block'] },
      {
        key: 'flexDirection',
        label: 'Flex 방향',
        type: 'select',
        options: ['row', 'column', 'row-reverse', 'column-reverse'],
      },
      {
        key: 'justifyContent',
        label: '가로 정렬 (justify)',
        type: 'select',
        options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around'],
      },
      {
        key: 'alignItems',
        label: '세로 정렬 (align)',
        type: 'select',
        options: ['flex-start', 'center', 'flex-end', 'stretch'],
      },
      { key: 'gap', label: '갭 (gap)', type: 'text' },
      { key: 'padding', label: '패딩 (padding)', type: 'text' },
      { key: 'backgroundColor', label: '배경색 (background color)', type: 'text' },
    ],
  },
  'my-note-box': {
    label: '노트박스',
    component: MyNoteBox,
    propsMeta: [
      { key: 'title', label: 'title', type: 'text' },
      { key: 'messageBefore', label: 'messageBefore', type: 'text' },
      { key: 'linkText', label: 'linkText', type: 'text' },
      { key: 'linkHref', label: 'linkHref', type: 'text' },
      { key: 'messageAfter', label: 'messageAfter', type: 'text' },
    ],
  },
  'my-card': {
    label: '카드',
    component: MyCard,
    propsMeta: [
      { key: 'title', label: '제목', type: 'text' },
      { key: 'content', label: '내용', type: 'textarea' },
      { key: 'color', label: '배경색', type: 'select', options: ['primary', 'info', 'warning'] },
    ],
  },
  'my-subject-text': {
    label: 'subject text',
    component: MySubjectText,
    propsMeta: [
      { key: 'title', label: '타이틀제목', type: 'text' },
      {
        key: 'icon',
        label: '아이콘',
        type: 'text',
      },
      {
        key: 'iconSize',
        label: '아이콘 크기',
        type: 'select',
        options: ['1', '2', '3', '4', '5'],
      },
      {
        key: 'size',
        label: '폰트 사이즈',
        type: 'select',
        options: ['sm', 'md', 'lg', 'xl'],
      },
      {
        key: 'weight',
        label: '폰트 두께',
        type: 'select',
        options: ['normal', 'medium', 'bold'],
      },
      {
        key: 'divider',
        label: '구분선',
        type: 'select',
        options: [true, false],
      },
    ],
  },
  'my-page-title': {
    label: 'Page Title',
    component: MyPageTitle,
    propsMeta: [
      { key: 'title', label: '페이지타이틀', type: 'text' },
      {
        key: 'breadcrumb',
        label: 'breadcrumb',
        type: 'text',
      },
    ],
  },
  'my-ag-grid': {
    label: 'AG GRid',
    component: MyAgGrid,
    propsMeta: [],
  },
  'my-ck-editor': {
    label: 'CKEditor',
    component: MyCkEditor,
    propsMeta: [],
  },
};
